name: Generate snake game

on:
  schedule: # execute every 2 hours
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      #- uses: Platane/snk@v2
      - uses: aelassas/snk@v2
        id: snake-gif
        with:
          github_user_name: Moai-san
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?color_snake=purple&color_dots=#575757,#bd3c65,#b3204e,#871b26,#5c040c
            dist/ocean.svg?color_snake=purple&color_dots=rgba(191,214,246,0.2),#bd3c65,#b3204e,#871b26,#5c040c

      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
